# 言語環境
export LANG=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8

# キーバインドをEmacsにする
bindkey -e

# 色の設定
autoload -U colors
colors


## 補完関連の設定
# zshの補完機能を有効にする
autoload -U compinit
compinit
# 補完時に大文字、小文字を区別しない
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
# 補完機能のグループ化の設定
zstyle ':completion:*' format '%B%d%b'
zstyle ':completion:*' group-name ''
# 補完候補に色を付ける
zstyle ':completion:*:default' list-colors '' 


## 履歴関連の設定
# メモリ上に保持する履歴の数
export HISTSIZE=100
# 履歴ファイルの保存先
export HISTFILE=$HOME/.zsh_history
# 履歴ファイルに保存される履歴の数
export SAVEHIST=1000
# 重複を記録しない
setopt hist_ignore_dups
# 開始と終了を記録
setopt extended_history
# zsh間で履歴を共有
setopt share_history


# プロンプトの設定ファイルを読み込む
source $HOME/.zsh_prompt

# ページャの設定
if type lv > /dev/null 2>&1 ; then
    export PAGER="lv"
fi

## エイリアス関連の設定
# OSに合わせてlsの色付け設定
case ${OSTYPE} in
	darwin*)
	alias ls="ls -GF"
	;;
	linux*)
	alias ls="ls --color=auto"
	;;
esac

# 種々の設定
alias la="ls -a"
alias ll="ls -l"
alias rr="rm -rf"
alias emacs="emacs -nw"


## grepの設定
# grepオプションの定義
export GREP_OPTIONS=""
# 何行目にマッチしたか表示
GREP_OPTIONS="-n $GREP_OPTIONS"
# バイナリファイルにはマッチさせない
GREP_OPTIONS="--binary-files=without-match $GREP_OPTIONS"
# マッチした文字に色をつける
GREP_OPTIONS="--color=auto $GREP_OPTIONS"


# 重複したPATHは登録しない
typeset -U PATH

# PATHの設定
PATH=/usr/local/bin:/usr/local/sbin:$PATH


## プログラミング言語関連の設定
# Perlのロケールの警告を表示させないようにする
export PERL_BADLANG=0

# rbenvの設定
# 初期化
eval "$(rbenv init -)"
# PATHの設定
PATH=$PATH:~/.rbenv/shims

## virtualenvの設定
# 環境が存在するパスを設定
WORKON_HOME=$HOME/.virtualenvs
# pipでパッケージを仮想環境にインストールする
export PIP_RESPECT_VIRTUALENV=true
# virtualenvwrapperの読み込み
source /usr/local/bin/virtualenvwrapper.sh
