## zsh環境設定
# 言語環境
export LANG=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8

# キーバインドをEmacsにする
bindkey -e

# 色の設定
autoload -U colors
colors

# 重複したPATHは登録しない
typeset -U PATH

# PATHの設定
PATH=/usr/local/bin:/usr/local/sbin:$PATH

# プロンプトの設定
PROMPT="[%n]%# "
RPROMPT="[%~] "

# ページャの設定
if type lv > /dev/null 2>&1 ; then
    export PAGER="lv"
fi


## 補完関連の設定
# zshの補完機能を有効にする
autoload -U compinit
# zcompdumpの出力先を変更
compinit -d $HOME/.zsh/zcompdump
# 補完時に大文字、小文字を区別しない
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
# 補完機能のグループ化の設定
zstyle ':completion:*' format '%B%d%b'
zstyle ':completion:*' group-name ''
# 補完候補に色を付ける
zstyle ':completion:*:default' list-colors ""


## 履歴関連の設定
# 履歴ファイルの保存先
export HISTFILE=$HOME/.zsh/zsh_history
# メモリ上に保持する履歴の数
export HISTSIZE=1000
# 履歴ファイルに保存される履歴の数
export SAVEHIST=10000
# 重複したコマンドは記録しない
setopt hist_ignore_all_dups
# 直前に同じコマンドを実行した場合は記録しない
setopt hist_ignore_dups
# コマンドを実行した時間と予想実行時間を記録
setopt extended_history
# zsh間で履歴を共有
setopt share_history
# cdで移動したディレクトリを記憶しておき、cd [TAB]で補完
setopt auto_pushd
# auto_pushdで重複したエントリは記録しない
setopt pushd_ignore_dups


## エイリアス関連の設定
# OSに合わせてlsの色付け設定
case ${OSTYPE} in
	darwin*)
	alias ls="ls -GF"
	;;
	linux*)
	alias ls="ls --color=auto"
	;;
esac

# 種々の設定
alias la="ls -a"
alias ll="ls -l"
alias rr="rm -rf"
alias emacs="emacs -nw"

# ^ で cd .. する
function cdup(){
	echo
	cd ..
	zle reset-prompt
}
zle -N cdup
bindkey '\^' cdup


## grepの設定
# grepオプションの定義
export GREP_OPTIONS=""
# 何行目にマッチしたか表示
GREP_OPTIONS="-n $GREP_OPTIONS"
# バイナリファイルにはマッチさせない
GREP_OPTIONS="--binary-files=without-match $GREP_OPTIONS"
# マッチした文字に色をつける
GREP_OPTIONS="--color=auto $GREP_OPTIONS"


## プログラミング言語関連の設定
# Perlのロケールの警告を表示させないようにする
export PERL_BADLANG=0

## rbenvの設定
# PATHの設定
PATH=$HOME/.rbenv/bin:$PATH
# 初期化
eval "$(rbenv init -)"

## pyenvの設定
# PATHの設定
PATH=$HOME/.pyenv/bin:$PATH
# 初期化
eval "$(pyenv init -)"

## 個別設定
# 個別設定ファイル(.zsh_local)があれば読み込む
if [ -e $HOME/.zsh_local ]; then
	source $HOME/.zsh_local
fi
