(source gnu)
(source melpa)

(depends-on "emacs-helm" :git "https://github.com/emacs-helm/helm.git")
(depends-on "scss-mode" :git "https://github.com/antonj/scss-mode.git")
(depends-on "web-mode" :git "https://github.com/fxbois/web-mode.git")
(depends-on "auto-complete" :git "https://github.com/auto-complete/auto-complete.git")
